# frozen_string_literal: true

source 'https://rubygems.org'

gem 'sinatra', '~> 4.0'
gem 'rackup'
gem 'rack-cors'
gem 'webrick'  # Rack server so rackup has a handler (required on Ruby 3.4+)
gem 'jwt'
gem 'bcrypt'
